trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs     
    displayName: 'Install Node.js'

  - script: |
      npm install -g npm@latest
      npm install -g dependency-check@0.6.0 || (cat /home/vsts/.npm/_logs/*-debug-0.log && exit 1)
    displayName: 'Update npm and install dependency-check'

# Install dependency-check
  - script: |
      npm install -g dependency-check@0.6.0
    displayName: 'Install dependency-check'

  # Run dependency-check
   
  - script: |
      dependency-check ./requirements.txt
    displayName: 'Run dependency-check'

  - script: |
      pytest --cov=.
    displayName: 'Run tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
    displayName: 'Archive app files'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifactName: 'app'
    displayName: 'Publish app artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Smart_Talent'
      appType: 'webAppLinux'
      appName: 'smarttalent'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
      appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'
    displayName: 'Deploy to Azure Web App'